_wandb:
    value:
        cli_version: 0.22.1
        e:
            kz4gd1d1p6rvj8tt5zl7p56f36unsrag:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: ppo.py
                codePathLocal: ppo.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "45338902528"
                email: yiting2083@gmail.com
                executable: /Library/Developer/CommandLineTools/usr/bin/python3
                host: yitings-Air.lan
                memory:
                    total: "17179869184"
                os: macOS-15.7-arm64-arm-64bit
                program: /Users/eating/Documents/sac/ppo/ppo.py
                python: CPython 3.9.6
                root: /Users/eating/Documents/sac/ppo
                startedAt: "2025-10-01T04:53:16.247979Z"
                writerId: kz4gd1d1p6rvj8tt5zl7p56f36unsrag
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 3
                - 24
            "4": 3.9.6
            "5": 0.22.1
            "12": 0.22.1
            "13": darwin-arm64
