_wandb:
    value:
        cli_version: 0.22.1
        e:
            z039trwwdfw65bsacsrpklj0da8b8cwc:
                codePath: ppo.py
                codePathLocal: ppo.py
                email: yiting2083@gmail.com
                executable: /Library/Developer/CommandLineTools/usr/bin/python3
                host: yitings-Air.lan
                os: macOS-15.7-arm64-arm-64bit
                program: /Users/eating/Documents/sac/ppo/ppo.py
                python: CPython 3.9.6
                root: /Users/eating/Documents/sac/ppo
                startedAt: "2025-10-01T04:51:51.164249Z"
                writerId: z039trwwdfw65bsacsrpklj0da8b8cwc
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 24
            "4": 3.9.6
            "5": 0.22.1
            "12": 0.22.1
            "13": darwin-arm64
