_wandb:
    value:
        cli_version: 0.22.1
        e:
            opcrpsaegnrnfsgmeqqeqxrjjmcara9v:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "10737418240"
                codePath: test.py
                codePathLocal: test.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "93464489984"
                email: yiting2083@gmail.com
                executable: /Users/eating/miniconda3/envs/py11/bin/python
                host: Mac.lan
                memory:
                    total: "17179869184"
                os: macOS-15.7.1-arm64-arm-64bit
                program: /Users/eating/Documents/sac/ppo/test.py
                python: CPython 3.11.13
                root: /Users/eating/Documents/sac/ppo
                startedAt: "2025-11-18T04:01:21.015143Z"
                writerId: opcrpsaegnrnfsgmeqqeqxrjjmcara9v
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "2":
                - 1
            "4": 3.11.13
            "5": 0.22.1
            "12": 0.22.1
            "13": darwin-arm64
