_wandb:
    value:
        cli_version: 0.22.1
        e:
            ezegcj7hfgb3g1ek8ntuq3w7vz9ioxpu:
                codePath: test.py
                codePathLocal: test.py
                email: yiting2083@gmail.com
                executable: /Users/eating/miniconda3/envs/py11/bin/python
                host: Mac.lan
                os: macOS-15.7.1-arm64-arm-64bit
                program: /Users/eating/Documents/sac/ppo/test.py
                python: CPython 3.11.13
                root: /Users/eating/Documents/sac/ppo
                startedAt: "2025-11-18T04:14:45.587309Z"
                writerId: ezegcj7hfgb3g1ek8ntuq3w7vz9ioxpu
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "2":
                - 1
            "4": 3.11.13
            "5": 0.22.1
            "12": 0.22.1
            "13": darwin-arm64
