_wandb:
    value:
        cli_version: 0.22.1
        e:
            7jtym2n1ymw2lzzy2h2sniw8vufktkxj:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: test.py
                codePathLocal: test.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "45333815296"
                email: yiting2083@gmail.com
                executable: /Library/Developer/CommandLineTools/usr/bin/python3
                host: yitings-Air.lan
                memory:
                    total: "17179869184"
                os: macOS-15.7-arm64-arm-64bit
                program: /Users/eating/Documents/sac/ppo/test.py
                python: CPython 3.9.6
                root: /Users/eating/Documents/sac/ppo
                startedAt: "2025-10-01T04:58:55.772171Z"
                writerId: 7jtym2n1ymw2lzzy2h2sniw8vufktkxj
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
            "2":
                - 1
            "4": 3.9.6
            "5": 0.22.1
            "12": 0.22.1
            "13": darwin-arm64
