_wandb:
    value:
        cli_version: 0.22.1
        e:
            cvckvip93hbaoqd8j2x84bamb6vb3x6w:
                codePath: wan.py
                codePathLocal: wan.py
                email: yiting2083@gmail.com
                executable: /Library/Developer/CommandLineTools/usr/bin/python3
                host: yitings-Air.lan
                os: macOS-15.7-arm64-arm-64bit
                program: /Users/eating/Documents/sac/ppo/wan.py
                python: CPython 3.9.6
                root: /Users/eating/Documents/sac/ppo
                startedAt: "2025-10-01T04:49:23.673056Z"
                writerId: cvckvip93hbaoqd8j2x84bamb6vb3x6w
        m: []
        python_version: 3.9.6
        t:
            "3":
                - 2
                - 16
            "4": 3.9.6
            "5": 0.22.1
            "12": 0.22.1
            "13": darwin-arm64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
