_wandb:
    value:
        cli_version: 0.22.1
        e:
            2wfvsitd98cfw2onh68fpau90f1dcnrw:
                codePath: ppo.py
                codePathLocal: ppo.py
                email: yiting2083@gmail.com
                executable: /Users/eating/miniconda3/envs/py11/bin/python
                host: Mac.lan
                os: macOS-15.7.1-arm64-arm-64bit
                program: /Users/eating/Documents/sac/ppo/ppo.py
                python: CPython 3.11.13
                root: /Users/eating/Documents/sac/ppo
                startedAt: "2025-11-18T01:53:14.632236Z"
                writerId: 2wfvsitd98cfw2onh68fpau90f1dcnrw
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 24
            "4": 3.11.13
            "5": 0.22.1
            "12": 0.22.1
            "13": darwin-arm64
